[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "baculo-tss-probe"
version = "0.1.0"
description = "Probing models and data pipelines for baculovirus transcription start site (TSS) prediction."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
  "datasets==4.6.1",    # nibi: error in loading pyarrow, something wrong with the arrow module
  "numpy>=2.4.1",    # nibi: 2.4.1
  "pandas>=3.0.0",    # nibi: 3.0.0
  "biopython==1.86",
  "scikit-learn==1.8.0",
  "torch==2.10.0",
  "transformers==5.3.0",
  "safetensors==0.7.0"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "ipykernel",
  "jupyter",
  "ruff",
  "black"
]
viz = [
  "matplotlib",
  "seaborn"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.black]
line-length = 100
target-version = ["py310"]
